-- LaluPay financial schema. All monetary values use NUMERIC; never floats.
create extension if not exists pgcrypto;
create type public.asset_code as enum ('PKR', 'USDT');
create type public.kyc_state as enum ('not_started', 'pending', 'approved', 'rejected');
create type public.tx_status as enum ('pending', 'completed', 'failed', 'cancelled', 'review');

create table public.system_config (id boolean primary key default true check (id), sandbox_mode boolean not null default true, licensing_obtained boolean not null default false, updated_at timestamptz not null default now());
insert into public.system_config (id) values (true) on conflict do nothing;
create table public.profiles (id uuid primary key references auth.users on delete cascade, username text unique check (username ~ '^[a-z0-9_]{3,32}$'), full_name text, mobile text unique, kyc_status public.kyc_state not null default 'not_started', kyc_tier smallint not null default 0 check (kyc_tier between 0 and 2), transaction_pin_hash text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.wallets (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, asset_code public.asset_code not null, balance_snapshot numeric(24,8) not null default 0, updated_at timestamptz not null default now(), unique(user_id, asset_code));
create table public.ledger_accounts (id uuid primary key default gen_random_uuid(), owner_id uuid references public.profiles on delete restrict, asset_code public.asset_code not null, account_code text not null unique, created_at timestamptz not null default now());
create table public.ledger_entries (id uuid primary key default gen_random_uuid(), transaction_group_id uuid not null, ledger_account_id uuid not null references public.ledger_accounts on delete restrict, asset_code public.asset_code not null, amount numeric(24,8) not null check (amount <> 0), created_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb);
create index ledger_entries_group_idx on public.ledger_entries(transaction_group_id);
create table public.transactions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete restrict, asset_code public.asset_code not null, amount numeric(24,8) not null, fee numeric(24,8) not null default 0, net_amount numeric(24,8) not null, type text not null, status public.tx_status not null default 'pending', reference text not null unique, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index transactions_user_created_idx on public.transactions(user_id, created_at desc);
create table public.idempotency_keys (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, key text not null, response jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique(user_id,key));
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, title text not null, body text not null, read_at timestamptz, created_at timestamptz not null default now());
create table public.p2p_advertisements (id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles on delete cascade, side text not null check (side in ('buy','sell')), asset_code public.asset_code not null check (asset_code = 'PKR'), price numeric(18,6) not null check(price > 0), min_amount numeric(18,2) not null check(min_amount > 0), max_amount numeric(18,2) not null check(max_amount >= min_amount), status text not null default 'active' check(status in ('active','paused','closed')), created_at timestamptz not null default now());
create table public.p2p_orders (id uuid primary key default gen_random_uuid(), advertisement_id uuid not null references public.p2p_advertisements on delete restrict, buyer_id uuid not null references public.profiles, seller_id uuid not null references public.profiles, amount numeric(18,2) not null check(amount > 0), status text not null default 'created', expires_at timestamptz not null, created_at timestamptz not null default now(), check(buyer_id <> seller_id));
create table public.order_messages (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.p2p_orders on delete cascade, sender_id uuid not null references public.profiles, body text not null check(length(body) <= 2000), created_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references public.profiles, action text not null, entity_type text not null, entity_id text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
alter table public.system_config enable row level security; alter table public.profiles enable row level security; alter table public.wallets enable row level security; alter table public.ledger_accounts enable row level security; alter table public.ledger_entries enable row level security; alter table public.transactions enable row level security; alter table public.idempotency_keys enable row level security; alter table public.notifications enable row level security; alter table public.p2p_advertisements enable row level security; alter table public.p2p_orders enable row level security; alter table public.order_messages enable row level security; alter table public.audit_logs enable row level security;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(id) values(new.id); insert into public.wallets(user_id,asset_code,balance_snapshot) values(new.id,'PKR',0),(new.id,'USDT',0); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
-- Server-only, atomic transfer RPC. Edge Functions call with a verified user identity.
create or replace function public.execute_internal_transfer(p_sender uuid, p_recipient uuid, p_asset public.asset_code, p_amount numeric, p_key text) returns uuid language plpgsql security definer set search_path = public as $$
declare v_group uuid := gen_random_uuid(); v_tx uuid := gen_random_uuid(); v_existing jsonb; v_balance numeric; begin
 if p_sender = p_recipient or p_amount <= 0 then raise exception 'Invalid transfer'; end if;
 select response into v_existing from idempotency_keys where user_id=p_sender and key=p_key; if found then return (v_existing->>'transaction_id')::uuid; end if;
 select coalesce(sum(le.amount),0) into v_balance from ledger_entries le join ledger_accounts la on la.id=le.ledger_account_id where la.owner_id=p_sender and la.asset_code=p_asset;
 if v_balance < p_amount then raise exception 'Insufficient funds'; end if;
 insert into ledger_entries(transaction_group_id,ledger_account_id,asset_code,amount) select v_group,id,p_asset,-p_amount from ledger_accounts where owner_id=p_sender and asset_code=p_asset;
 insert into ledger_entries(transaction_group_id,ledger_account_id,asset_code,amount) select v_group,id,p_asset,p_amount from ledger_accounts where owner_id=p_recipient and asset_code=p_asset;
 insert into transactions(id,user_id,asset_code,amount,net_amount,type,status,reference) values(v_tx,p_sender,p_asset,p_amount,-p_amount,'transfer_out','completed','TRF-'||v_tx),(gen_random_uuid(),p_recipient,p_asset,p_amount,p_amount,'transfer_in','completed','TRF-'||v_tx||'-IN');
 insert into idempotency_keys(user_id,key,response) values(p_sender,p_key,jsonb_build_object('transaction_id',v_tx)); return v_tx; end; $$;
revoke all on function public.execute_internal_transfer(uuid,uuid,public.asset_code,numeric,text) from public;
